' ----------------------------------------------
' Script generated by SIwave
' Tue Apr 20 08:41:09 2021
' ----------------------------------------------
Dim oAnsoftApp
Dim oDesktop
Dim oProjects
Dim oProject
Dim projectPath
Dim oFSO
Dim oTextFile
Set oAnsoftApp = CreateObject("Ansoft.ElectronicsDesktop.2020.2")
Set oDesktop = oAnsoftApp.GetAppDesktop()
oDesktop.RestoreWindow

Set oProjects = oDesktop.GetProjects
For Each oProject in oProjects
  projectPath = oProject.GetPath() + oProject.GetName()
  If projectPath = "C:/Users/guven/Desktop/-AESK-/ALL Documents/Drive Electric 2020/Elektrik/Motor Driver/BLDC Driver/[1] Hardware/[1] Power/Project Outputs for Power/odb/SIWAWE DENEME1.siwaveresults/Designer/SIwizard1" Then
    Set oFSO = CreateObject("Scripting.FileSystemObject")
    Set oTextFile = oFSO.CreateTextFile("C:/Users/guven/Desktop/-AESK-/ALL Documents/Drive Electric 2020/Elektrik/Motor Driver/BLDC Driver/[1] Hardware/[1] Power/Project Outputs for Power/odb/SIWAWE DENEME1.siwaveresults/Designer/AEDTProjectAlreadyOpen.tmp", True)
    oTextFile.Close
    Exit For
  End If
Next
